### ISSUE TITLE
In order to better detect the external IP

### ISSUE THREAD

**Issue by potap1978** [RomikB/amneziawg-install#3]
In order to better detect the external IP

replace
SERVER_PUB_IP=$(ip -4 addr | sed -ne 's|^.* inet \([^/]*\)/.* scope global.*$|\1|p' | awk '{print $1}' | head -1)

with
SERVER_PUB_IP=$(curl -s http://whatismijnip.nl |cut -d " " -f 5)

or
SERVER_PUB_IP=$(curl -s icanhazip.com)

or or
curl -s ipv4.icanhazip.com
curl -s ipv6.icanhazip.com
👍

**Comment by RomikB** [comment]
I don't want to add a dependency to external web site.
